from django.urls import path
from . import views
urlpatterns = [
    path('login/',views.logInView,name="login"),
    path('register/',views.registerView, name="register"),
    path('',views.homeView, name="home"),
    path('crypto/',views.cryptoView,name="crypto"),
    path('bitcoin/',views.bitcoinView,name="bitcoin"),
    path('blockchain/',views.blockchainView,name="blockchain"),
    path('correlation/',views.correlationView,name="correlation"),
    path('etherium/',views.etheriumView,name="etherium"),
    path('nfts/',views.whatView,name="what"),
    path('wise/',views.wiseView,name="wise"),
    path('add_crypto/',views.addCryptoView),
    path('crypto_quiz/',views.cryptoQuizView,name="cryptoQuiz"),
    path('add_blockchain/',views.addBlockchainView),
    path('blockchain_quiz/',views.BlockchainQuizView,name="blockchainQuiz"),
    path('add_bitcoin/',views.addBitcoinView),
    path('bitcoin_quiz/',views.BitcoinQuizView,name="bitcoinQuiz"),
    path('add_etherium/',views.addEtheriumView),
    path('etherium_quiz/',views.EtheriumQuizView,name="EtheriumQuiz"),
    path('add_nfts/',views.addNftsView),
    path('nfts_quiz/',views.NftsQuizView,name="NftsQuiz"),
    path('add_correlation/',views.addCorrelationView),
    path('correlation_quiz/',views.CorrelationQuizView,name="CorrelationQuiz"),
    path('add_wise/',views.addWiseView),
    path('wise_quiz/',views.WiseQuizView,name="WiseQuiz"),
    path('crypto_second/',views.cryptoSecondView,name="SecondCrypto"),
    path('bitcoin_second/',views.bitcoinSecondView,name="SecondBitcoin"),
    path('bitcoin_third/',views.bitcoinThirdView,name="ThirdBitcoin"),
    path('etherium_second/',views.etheriumSecondView,name="SecondEtherium"),
    path('correlation_second/',views.correlationSecondView,name="SecondCorrelation"),
    path('correlation_third/',views.correlationThirdView,name="ThirdCorrelation"),
    path('correlation_fourth/',views.correlationFourthView,name="FourthCorrelation"),
    path('add_comment/',views.AddCommentsView,name="addComment"),
    path('comments/',views.CommentsView,name="comments"),
    path('logout/',views.logoutView,name="logout")
]
